behaviors:
  RollerBall:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 2000
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.150
      lambd: 0.99
      num_epoch: 25
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 64
      num_layers: 10
      use_recurrent: true
      sequence_length: 64
      memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 600000
    time_horizon: 1000
    summary_freq: 10000